name: build_and_upload

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: |
        chmod 755 gen_test_dir.sh
        ./gen_test_dir.sh
        cargo test --verbose

    - name: Copy artifact
      run: mkdir -p release && cp target/release/main release/

    - uses: actions/upload-artifact@v1
      with:
        name: rm-old_${{ github.sha }}_amd64
        path: release
